### ISSUE TITLE
I Hate QT Graphics

### ISSUE THREAD

**Issue by win32kbase** [cademtz/Animate-Together#1]
I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics I Hate QT Graphics

**Comment by cademtz** [comment]
I hate Qt Graphics
